Add check on build timestamp to download from manta intead of download.joyent.com
Signed-off-by: Jacques Marneweck <jacques@powertrip.co.za>

diff --git a/writekey b/writekey
--- a/writekey
+++ b/writekey
@@ -44,10 +44,22 @@ fi
 
 cd /var/tmp/usbimg
 
-wget --no-check-cert https://download.joyent.com/pub/iso/smartos-${IMAGE}-USB.img.bz2
-if [ $? -eq 1 ]; then
-  echo "Unable to download the smartos ${IMAGE} build."
-  exit 2
+#
+# Download July 2013 and later releases from Manta in us-east-1
+# else from download.joyent.com for older builds.
+#
+if [[ $(echo ${IMAGE} | cut -c 1-6) -ge 201307 ]]; then
+  wget --no-check-cert https://us-east.manta.joyent.com/Joyent_Dev/public/SmartOS/20130711T230351Z/smartos-${IMAGE}-USB.img.bz2
+  if [ $? -eq 1 ]; then
+    echo "Unable to download the SmartOS ${IMAGE} USB Key build from Manta."
+    exit 2
+  fi
+else
+  wget --no-check-cert https://download.joyent.com/pub/iso/smartos-${IMAGE}-USB.img.bz2
+  if [ $? -eq 1 ]; then
+    echo "Unable to download the SmartOS ${IMAGE} USB Key build from download.joyent.com."
+    exit 2
+  fi
 fi
 
 bunzip2 smartos-${IMAGE}-USB.img.bz2
